insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (1, '06-Feb-2023', 5, 59);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (2, '14-Sep-2022', 1, 36);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (3, '08-Feb-2023', 1, 70);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (4, '27-Aug-2022', 3, 61);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (5, '09-Aug-2022', 6, 22);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (6, '24-Jun-2022', 2, 79);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (7, '11-Mar-2023', 7, 4);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (8, '12-Mar-2023', 6, 96);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (9, '26-Jan-2023', 5, 1);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (10, '02-Jul-2022', 7, 97);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (11, '27-Jul-2022', 2, 68);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (12, '23-Feb-2023', 6, 97);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (13, '28-Dec-2022', 2, 84);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (14, '17-May-2022', 3, 45);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (15, '07-Jul-2022', 1, 21);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (16, '08-Aug-2022', 5, 14);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (17, '11-Sep-2022', 2, 16);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (18, '17-Nov-2022', 2, 16);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (19, '17-Feb-2023', 2, 75);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (20, '18-Apr-2022', 7, 41);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (21, '25-Jul-2022', 5, 35);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (22, '10-Nov-2022', 2, 54);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (23, '08-Jan-2023', 5, 88);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (24, '28-Aug-2022', 5, 31);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (25, '29-Dec-2022', 2, 82);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (26, '08-Feb-2023', 3, 40);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (27, '13-Jul-2022', 6, 82);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (28, '24-Sep-2022', 7, 46);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (29, '07-May-2022', 1, 91);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (30, '14-Aug-2022', 7, 74);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (31, '18-Mar-2023', 5, 98);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (32, '06-Feb-2023', 3, 71);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (33, '07-Jun-2022', 4, 58);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (34, '02-Apr-2022', 6, 79);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (35, '13-Jun-2022', 7, 26);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (36, '20-Jan-2023', 3, 35);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (37, '08-Jan-2023', 1, 79);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (38, '29-Dec-2022', 3, 71);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (39, '16-Aug-2022', 1, 4);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (40, '18-Apr-2022', 1, 60);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (41, '21-Feb-2023', 3, 54);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (42, '26-Dec-2022', 4, 2);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (43, '29-Apr-2022', 7, 45);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (44, '10-Nov-2022', 4, 56);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (45, '27-Dec-2022', 6, 53);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (46, '26-Nov-2022', 2, 76);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (47, '29-Sep-2022', 7, 94);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (48, '14-Oct-2022', 5, 22);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (49, '04-Mar-2023', 2, 65);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (50, '03-Aug-2022', 6, 5);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (51, '02-May-2022', 1, 42);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (52, '30-Apr-2022', 1, 15);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (53, '05-Feb-2023', 1, 46);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (54, '15-Feb-2023', 3, 45);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (55, '16-Feb-2023', 6, 31);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (56, '06-Feb-2023', 5, 21);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (57, '29-Oct-2022', 6, 37);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (58, '10-Jun-2022', 6, 76);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (59, '03-Apr-2022', 2, 58);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (60, '19-Jun-2022', 7, 46);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (61, '22-Mar-2023', 1, 65);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (62, '08-Apr-2022', 5, 53);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (63, '27-Mar-2022', 5, 72);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (64, '16-Jan-2023', 7, 26);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (65, '08-Jun-2022', 6, 38);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (66, '25-Jan-2023', 3, 81);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (67, '06-Dec-2022', 1, 79);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (68, '24-Sep-2022', 6, 90);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (69, '03-Jun-2022', 3, 90);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (70, '09-Dec-2022', 5, 73);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (71, '19-Mar-2023', 5, 92);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (72, '20-Dec-2022', 1, 78);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (73, '22-Aug-2022', 7, 36);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (74, '27-Mar-2022', 7, 26);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (75, '07-Jun-2022', 4, 94);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (76, '20-Jul-2022', 2, 21);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (77, '27-May-2022', 4, 10);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (78, '29-Jan-2023', 5, 15);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (79, '10-Nov-2022', 7, 26);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (80, '29-Jul-2022', 7, 55);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (81, '14-Jun-2022', 2, 12);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (82, '28-Jun-2022', 5, 76);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (83, '15-Jul-2022', 2, 17);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (84, '20-Oct-2022', 3, 45);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (85, '26-Dec-2022', 2, 90);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (86, '11-May-2022', 5, 8);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (87, '22-Aug-2022', 2, 4);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (88, '30-Sep-2022', 3, 3);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (89, '30-Mar-2022', 6, 51);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (90, '23-Jul-2022', 6, 53);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (91, '04-Mar-2023', 4, 63);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (92, '10-May-2022', 1, 67);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (93, '17-Sep-2022', 6, 49);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (94, '22-Feb-2023', 4, 43);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (95, '11-Jun-2022', 3, 42);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (96, '10-Feb-2023', 1, 31);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (97, '22-Jul-2022', 2, 5);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (98, '17-Jun-2022', 3, 9);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (99, '20-Feb-2023', 5, 31);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (100, '03-Sep-2022', 2, 66);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (101, '03-Nov-2022', 1, 9);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (102, '10-Oct-2022', 3, 66);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (103, '20-Jan-2023', 4, 51);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (104, '12-Sep-2022', 6, 54);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (105, '11-Jul-2022', 1, 35);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (106, '05-Apr-2022', 1, 85);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (107, '01-Oct-2022', 3, 6);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (108, '21-Nov-2022', 6, 17);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (109, '10-Oct-2022', 3, 23);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (110, '11-Dec-2022', 5, 91);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (111, '15-Oct-2022', 6, 28);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (112, '11-Jun-2022', 2, 1);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (113, '12-Sep-2022', 5, 17);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (114, '22-Oct-2022', 2, 96);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (115, '31-Jul-2022', 5, 96);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (116, '04-Oct-2022', 5, 93);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (117, '09-Oct-2022', 2, 61);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (118, '03-Dec-2022', 6, 9);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (119, '27-Mar-2022', 6, 91);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (120, '24-Jun-2022', 4, 41);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (121, '03-Jun-2022', 2, 68);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (122, '11-Jan-2023', 5, 11);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (123, '19-Nov-2022', 7, 82);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (124, '03-Apr-2022', 6, 12);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (125, '30-Aug-2022', 6, 65);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (126, '02-Nov-2022', 6, 22);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (127, '17-Oct-2022', 2, 44);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (128, '08-Aug-2022', 2, 45);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (129, '23-Jun-2022', 3, 10);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (130, '27-Oct-2022', 2, 55);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (131, '15-Apr-2022', 4, 23);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (132, '13-Oct-2022', 2, 5);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (133, '18-Apr-2022', 5, 5);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (134, '14-Sep-2022', 1, 54);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (135, '27-May-2022', 7, 10);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (136, '22-Apr-2022', 5, 32);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (137, '17-Apr-2022', 2, 14);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (138, '08-Nov-2022', 3, 15);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (139, '18-Aug-2022', 3, 18);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (140, '15-Nov-2022', 3, 61);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (141, '03-Dec-2022', 6, 31);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (142, '13-Nov-2022', 6, 64);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (143, '07-Apr-2022', 3, 72);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (144, '20-Oct-2022', 5, 46);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (145, '01-Sep-2022', 3, 20);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (146, '29-Nov-2022', 3, 36);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (147, '11-Apr-2022', 2, 55);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (148, '01-Jan-2023', 1, 31);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (149, '19-Feb-2023', 4, 59);
insert into customer_order (Order_ID, Order_date, Payment_type_ID, CustomerID) values (150, '11-Mar-2023', 2, 84);


insert into order_details (Order_details_ID, Product_ID, Order_ID) values (1, 31, 2);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (2, 36, 127);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (3, 47, 136);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (4, 22, 101);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (5, 50, 74);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (6, 22, 33);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (7, 4, 26);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (8, 47, 21);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (9, 43, 144);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (10, 3, 11);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (11, 49, 97);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (12, 41, 85);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (13, 50, 118);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (14, 34, 125);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (15, 23, 9);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (16, 36, 91);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (17, 7, 84);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (18, 11, 42);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (19, 49, 149);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (20, 48, 31);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (21, 29, 131);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (22, 23, 13);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (23, 22, 28);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (24, 41, 20);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (25, 25, 3);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (26, 1, 117);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (27, 39, 75);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (28, 42, 139);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (29, 45, 43);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (30, 45, 3);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (31, 17, 94);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (32, 38, 3);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (33, 22, 46);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (34, 14, 4);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (35, 27, 23);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (36, 30, 77);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (37, 39, 21);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (38, 5, 5);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (39, 49, 75);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (40, 38, 104);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (41, 46, 100);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (42, 24, 59);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (43, 13, 140);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (44, 26, 41);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (45, 15, 104);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (46, 30, 137);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (47, 39, 121);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (48, 7, 15);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (49, 11, 20);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (50, 1, 83);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (51, 12, 48);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (52, 48, 76);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (53, 13, 39);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (54, 13, 70);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (55, 21, 39);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (56, 9, 38);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (57, 28, 99);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (58, 47, 22);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (59, 7, 83);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (60, 35, 22);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (61, 43, 69);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (62, 21, 107);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (63, 43, 37);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (64, 20, 131);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (65, 23, 65);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (66, 12, 85);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (67, 48, 20);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (68, 42, 134);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (69, 32, 1);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (70, 15, 14);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (71, 21, 122);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (72, 27, 135);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (73, 43, 124);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (74, 46, 61);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (75, 36, 14);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (76, 17, 4);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (77, 8, 11);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (78, 27, 46);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (79, 18, 2);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (80, 36, 131);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (81, 48, 71);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (82, 5, 64);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (83, 30, 51);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (84, 29, 81);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (85, 1, 46);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (86, 36, 43);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (87, 2, 92);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (88, 13, 131);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (89, 18, 17);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (90, 25, 135);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (91, 3, 44);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (92, 12, 68);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (93, 37, 117);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (94, 18, 72);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (95, 38, 148);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (96, 11, 3);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (97, 20, 74);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (98, 38, 74);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (99, 8, 97);
insert into order_details (Order_details_ID, Product_ID, Order_ID) values (100, 19, 146);